import { useDispatch, useSelector } from "react-redux";
import { useEffect, useState } from "react";
import { clearAuthState, forgotPassword } from "@/store/auth-slice/user";
import MetaData from "../../extras/MetaData";
import { toast } from "react-toastify";
import { useNavigate, Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Mail, ArrowLeft, ArrowRight, ShieldCheck } from "lucide-react";

const ForgotPassword = () => {
  const [email, setEmail] = useState(""); const dispatch = useDispatch(); const navigate = useNavigate(); const { loading, error, success } = useSelector((state) => state.auth);
  const submit = (e) => { e.preventDefault(); if (!email.trim()) return toast.error("Please enter your email"); dispatch(forgotPassword(email.trim())); };
  useEffect(() => { if (success) { toast.success("OTP sent! Please check your email."); const timer = setTimeout(() => navigate("/verify-otp"), 1200); return () => clearTimeout(timer); } if (error) toast.error(error); }, [success, error, navigate]);
  useEffect(() => () => { dispatch(clearAuthState()); }, [dispatch]);
  return <><MetaData title="Forgot Password | Samridhi Enterprises" description="Recover your Samridhi Enterprises account securely." keywords="forgot password, account recovery, Samridhi Enterprises"/><main className="min-h-[calc(100vh-140px)] bg-[var(--surface-1)] px-4 py-10 sm:px-6"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="mx-auto w-full max-w-xl rounded-[2rem] border border-[var(--line)] bg-[var(--surface-0)] p-6 shadow-[0_24px_80px_rgba(15,23,42,.1)] sm:p-10 lg:p-14"><div className="mx-auto max-w-md"><div className="mb-7 flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-600/20"><ShieldCheck className="h-6 w-6"/></div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Account recovery</p><h1 className="mt-2 text-3xl font-black tracking-tight text-[var(--text-strong)]">Forgot your password?</h1><p className="mt-3 text-sm leading-6 text-[var(--text-muted)]">Enter your registered email. We’ll send an OTP so you can securely create a new password.</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.16em] text-[var(--text-muted)]">Email address</span><span className="relative block"><Mail className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-blue-500"/><input id="forgot-email" type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" className="w-full rounded-xl border border-[var(--line)] bg-[var(--surface-1)] py-3.5 pl-11 pr-4 text-sm text-[var(--text-strong)] outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></span></label><motion.button whileHover={{ y: -1 }} whileTap={{ scale: .98 }} disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3.5 text-sm font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700 disabled:opacity-60">{loading ? "Sending OTP…" : <>Send OTP <ArrowRight className="h-4 w-4"/></>}</motion.button></form><div className="mt-7 flex justify-center"><Link to="/login" className="inline-flex items-center gap-2 text-sm font-bold text-[var(--text-muted)] hover:text-blue-600"><ArrowLeft className="h-4 w-4"/>Back to sign in</Link></div></div></motion.div></main></>;
};
export default ForgotPassword;