import { useDispatch, useSelector } from "react-redux";
import { useEffect, useState } from "react";
import { clearAuthState, verifyOtp } from "@/store/auth-slice/user";
import { useNavigate, Link } from "react-router-dom";
import MetaData from "../../extras/MetaData";
import { toast } from "react-toastify";
import { motion } from "framer-motion";
import { KeyRound, Mail, ArrowLeft, ArrowRight } from "lucide-react";

export default function VerifyOtp() {
  const [email, setEmail] = useState(""); const [otp, setOtp] = useState(""); const dispatch = useDispatch(); const navigate = useNavigate(); const { loading, error, success } = useSelector((s) => s.auth);
  const submit = (e) => { e.preventDefault(); if (!email || !/^\d{6}$/.test(otp)) return toast.error("Enter a valid email and 6-digit OTP"); dispatch(verifyOtp({ email, otp })); };
  useEffect(() => { if (success && otp) { toast.success("OTP verified!"); localStorage.setItem("resetEmail", email); localStorage.setItem("resetOtp", otp); const timer = setTimeout(() => { navigate("/reset-password"); dispatch(clearAuthState()); }, 900); return () => clearTimeout(timer); } if (error) toast.error(error); }, [success, error, navigate, otp, dispatch, email]);
  useEffect(() => () => dispatch(clearAuthState()), [dispatch]);
  return <><MetaData title="Verify OTP | Samridhi Enterprises" description="Verify your password reset OTP securely." keywords="verify OTP, password reset, Samridhi Enterprises"/><main className="min-h-[calc(100vh-140px)] bg-[var(--surface-1)] px-4 py-10 sm:px-6"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="mx-auto w-full max-w-xl rounded-[2rem] border border-[var(--line)] bg-[var(--surface-0)] p-6 shadow-[0_24px_80px_rgba(15,23,42,.1)] sm:p-10 lg:p-14"><div className="mx-auto max-w-md"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-600/20"><KeyRound className="h-6 w-6"/></div><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-blue-600">Password recovery</p><h1 className="mt-2 text-3xl font-black text-[var(--text-strong)]">Verify your OTP</h1><p className="mt-3 text-sm leading-6 text-[var(--text-muted)]">Confirm the code sent to your email before choosing a new password.</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.16em] text-[var(--text-muted)]">Email</span><span className="relative block"><Mail className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-blue-500"/><input type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" className="w-full rounded-xl border border-[var(--line)] bg-[var(--surface-1)] py-3.5 pl-11 pr-4 text-sm text-[var(--text-strong)] outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></span></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.16em] text-[var(--text-muted)]">OTP</span><input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={otp} onChange={(e) => setOtp(e.target.value.replace(/\D/g, "").slice(0, 6))} placeholder="000000" className="w-full rounded-xl border border-[var(--line)] bg-[var(--surface-1)] px-4 py-4 text-center text-xl font-black tracking-[.3em] text-[var(--text-strong)] outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></label><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3.5 text-sm font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700 disabled:opacity-60">{loading ? "Verifying…" : <>Verify OTP <ArrowRight className="h-4 w-4"/></>}</button></form><div className="mt-7 flex justify-center"><Link to="/forgot-password" className="inline-flex items-center gap-2 text-sm font-bold text-[var(--text-muted)] hover:text-blue-600"><ArrowLeft className="h-4 w-4"/>Back to recovery</Link></div></div></motion.div></main></>;
}