import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import { Mail, LockKeyhole, Eye, EyeOff, UserRound, ArrowRight, CheckCircle2 } from "lucide-react";
import { useSelector, useDispatch } from "react-redux";
import { toast } from "react-toastify";
import { clearError, signupUser } from "@/store/auth-slice/user";
import { PASSWORD_REQUIREMENTS } from "../../utils/passwordRequirements";

const Signup = () => {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false);
  const dispatch = useDispatch(); const navigate = useNavigate(); const { error, loading } = useSelector((state) => state.auth);
  useEffect(() => { if (error) { toast.error(error); dispatch(clearError()); } }, [dispatch, error]);
  const submit = async (e) => { e.preventDefault(); if (!name || !email || !password) return toast.error("Please fill in all fields"); if (!PASSWORD_REQUIREMENTS.every((r) => r.test(password))) return toast.error("Password does not meet complexity requirements!"); try { await dispatch(signupUser({ name, email, password })).unwrap(); toast.success("Welcome to Samridhi Enterprises!"); navigate("/login"); } catch { /* Redux error state is displayed above. */ } };
  return <>
    <main className="min-h-[calc(100vh-140px)] bg-[var(--surface-1)] px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto grid w-full max-w-6xl overflow-hidden rounded-[2rem] border border-[var(--line)] bg-[var(--surface-0)] shadow-[0_24px_80px_rgba(15,23,42,.12)] lg:grid-cols-[.9fr_1.1fr]">
      <motion.section initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="relative hidden overflow-hidden bg-slate-950 p-10 text-white lg:flex lg:min-h-[650px] lg:flex-col lg:justify-between"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(37,99,235,.35),transparent_42%),radial-gradient(circle_at_10%_90%,rgba(14,165,233,.18),transparent_38%)]"/><div className="relative"><p className="text-xs font-bold uppercase tracking-[.22em] text-blue-300">Join the community</p><h1 className="mt-3 max-w-md text-4xl font-black leading-tight">Build a better garage experience.</h1><p className="mt-5 max-w-md text-sm leading-6 text-slate-300">Create your account to save products, track orders and get support when you need it.</p></div><div className="relative space-y-3">{["Track every order in one place","Save products for later","Get dedicated support"].map((text) => <div key={text} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm font-semibold"><CheckCircle2 className="h-5 w-5 text-blue-400"/>{text}</div>)}</div></motion.section>
      <motion.section initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="p-6 sm:p-10 lg:p-14"><div className="mx-auto max-w-lg"><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Create account</p><h2 className="mt-2 text-3xl font-black tracking-tight text-[var(--text-strong)] sm:text-4xl">Welcome to Samridhi.</h2><p className="mt-2 text-sm text-[var(--text-muted)]">Set up your account in less than a minute.</p></div>
        <form onSubmit={submit} className="space-y-5"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.16em] text-[var(--text-muted)]">Full name</span><span className="relative block"><UserRound className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-blue-500"/><input id="signup-name" autoComplete="name" value={name} onChange={(e) => setName(e.target.value)} placeholder="Your full name" className="w-full rounded-xl border border-[var(--line)] bg-[var(--surface-1)] py-3.5 pl-11 pr-4 text-sm text-[var(--text-strong)] outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></span></label>
          <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.16em] text-[var(--text-muted)]">Email</span><span className="relative block"><Mail className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-blue-500"/><input id="signup-email" type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" className="w-full rounded-xl border border-[var(--line)] bg-[var(--surface-1)] py-3.5 pl-11 pr-4 text-sm text-[var(--text-strong)] outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></span></label>
          <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.16em] text-[var(--text-muted)]">Password</span><span className="relative block"><LockKeyhole className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-blue-500"/><input id="signup-password" type={showPassword ? "text" : "password"} autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Create a strong password" className="w-full rounded-xl border border-[var(--line)] bg-[var(--surface-1)] py-3.5 pl-11 pr-12 text-sm text-[var(--text-strong)] outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/><button type="button" onClick={() => setShowPassword((v) => !v)} aria-label={showPassword ? "Hide password" : "Show password"} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-2 text-[var(--text-muted)] hover:text-blue-600">{showPassword ? <EyeOff className="h-4 w-4"/> : <Eye className="h-4 w-4"/>}</button></span></label>
          <AnimatePresence>{password && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }} className="overflow-hidden rounded-xl border border-[var(--line)] bg-[var(--surface-1)] p-4"><p className="mb-3 text-xs font-bold uppercase tracking-[.12em] text-[var(--text-muted)]">Password requirements</p><div className="grid grid-cols-1 gap-2 sm:grid-cols-2">{PASSWORD_REQUIREMENTS.map((r) => { const ok = r.test(password); return <div key={r.id} className={`flex items-center gap-2 text-xs font-semibold ${ok ? "text-emerald-600" : "text-[var(--text-muted)]"}`}><span className={`grid h-4 w-4 place-items-center rounded-full ${ok ? "bg-emerald-500 text-white" : "bg-[var(--line)]"}`}>{ok ? "✓" : ""}</span>{r.label}</div>; })}</div></motion.div>}</AnimatePresence>
          <motion.button whileHover={{ y: -1 }} whileTap={{ scale: .98 }} disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3.5 text-sm font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700 disabled:opacity-60">{loading ? "Creating account…" : <>Create account <ArrowRight className="h-4 w-4"/></>}</motion.button>
        </form><p className="mt-7 text-center text-sm text-[var(--text-muted)]">Already have an account? <Link to="/login" className="font-bold text-blue-600 hover:underline">Sign in</Link></p></div></motion.section>
    </div></main></>;
};
export default Signup;