import { useState, useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { motion } from "framer-motion";
import { useLocation, useNavigate } from "react-router-dom";
import { resendOtp, verifyEmailOtp } from "@/store/auth-slice/otpSlice";
import { toast } from "react-toastify";
import MetaData from "../../extras/MetaData";
import { MailCheck, ArrowRight, RefreshCw } from "lucide-react";

export default function VerifyEmail() {
  const dispatch = useDispatch(); const navigate = useNavigate(); const location = useLocation(); const { loading, successMessage, verifyEmail } = useSelector((s) => s.otp); const { user, isAuthenticated } = useSelector((s) => s.auth); const [otp, setOtp] = useState("");
  const redirect = location.search ? location.search.split("=")[1] : (isAuthenticated ? "/" : "/login");
  useEffect(() => { if (!isAuthenticated) { toast.error("Please log in to verify your email"); navigate("/login"); } }, [isAuthenticated, navigate]);
  useEffect(() => { if (verifyEmail) { toast.success(successMessage); navigate(redirect); } }, [verifyEmail, navigate, redirect, successMessage]);
  const submit = (e) => { e.preventDefault(); if (!/^\d{6}$/.test(otp)) return toast.error("OTP must be 6 digits"); dispatch(verifyEmailOtp({ email: user?.email, otp })); };
  return <><MetaData title="Verify Email | Samridhi Enterprises" description="Verify your email address securely." keywords="email verification, Samridhi Enterprises"/><main className="min-h-[calc(100vh-140px)] bg-[var(--surface-1)] px-4 py-10 sm:px-6"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="mx-auto w-full max-w-xl rounded-[2rem] border border-[var(--line)] bg-[var(--surface-0)] p-6 text-center shadow-[0_24px_80px_rgba(15,23,42,.1)] sm:p-10 lg:p-14"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-600/20"><MailCheck className="h-7 w-7"/></div><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-blue-600">Email verification</p><h1 className="mt-2 text-3xl font-black text-[var(--text-strong)]">Verify your email</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[var(--text-muted)]">Enter the 6-digit code sent to <strong className="text-[var(--text-strong)]">{user?.email || "your email"}</strong>.</p><form onSubmit={submit} className="mx-auto mt-8 max-w-sm space-y-4"><input aria-label="Email verification OTP" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={otp} onChange={(e) => setOtp(e.target.value.replace(/\D/g, "").slice(0, 6))} placeholder="000000" className="w-full rounded-xl border border-[var(--line)] bg-[var(--surface-1)] px-4 py-4 text-center text-2xl font-black tracking-[.35em] text-[var(--text-strong)] outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3.5 text-sm font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700 disabled:opacity-60">{loading ? "Verifying…" : <>Verify email <ArrowRight className="h-4 w-4"/></>}</button></form><button type="button" onClick={() => dispatch(resendOtp(user?.email))} disabled={loading} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[var(--text-muted)] hover:text-blue-600"><RefreshCw className="h-4 w-4"/>Resend code</button></motion.div></main></>;
}