import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { toast } from "react-toastify";
import { MapPin, Plus, Pencil, Trash2, Star, Check, X, Home, Building2 } from "lucide-react";
import { getMyAddresses, addAddress, updateAddress, deleteAddress, setDefaultAddress, clearAddressError, clearAddressSuccess } from "@/store/order/addressSlice";
import Loader from "../../extras/Loader";
import SEO from "../../components/SEO";

const EMPTY_FORM = { label:"", fullName:"", phone:"", addressLine:"", city:"", state:"", pincode:"", isDefault:false };
const AddressIcon = ({ label }) => String(label || "").toLowerCase().includes("office") ? <Building2 className="w-5 h-5" /> : <Home className="w-5 h-5" />;

export default function MyAddresses() {
 const dispatch=useDispatch(); const {addresses,loading,actionLoading,error,success}=useSelector(s=>s.address);
 const [showModal,setShowModal]=useState(false),[editingId,setEditingId]=useState(null),[form,setForm]=useState(EMPTY_FORM),[confirmDelete,setConfirmDelete]=useState(null),[formError,setFormError]=useState("");
 useEffect(()=>{dispatch(getMyAddresses())},[dispatch]);
 useEffect(()=>{if(success){setShowModal(false);setEditingId(null);setForm(EMPTY_FORM);setConfirmDelete(null);dispatch(clearAddressSuccess())}},[success,dispatch]);
 useEffect(()=>{if(error){toast.error(error);dispatch(clearAddressError())}},[error,dispatch]);
 const openCreate=()=>{setEditingId(null);setForm(EMPTY_FORM);setFormError("");setShowModal(true)};
 const openEdit=a=>{setEditingId(a._id);setForm({label:a.label||"",fullName:a.fullName||"",phone:a.phone||"",addressLine:a.addressLine||"",city:a.city||"",state:a.state||"",pincode:a.pincode||"",isDefault:a.isDefault||false});setFormError("");setShowModal(true)};
 const change=e=>{const {name,value,type,checked}=e.target;setForm(f=>({...f,[name]:type==="checkbox"?checked:value}))};
 const submit=()=>{setFormError("");const required=["fullName","phone","addressLine","city","pincode"];if(required.some(k=>!String(form[k]).trim()))return setFormError("Please fill all required fields");if(!/^\d{6}$/.test(form.pincode))return setFormError("Enter a valid 6-digit pincode");if(editingId)dispatch(updateAddress({id:editingId,payload:form}));else dispatch(addAddress(form))};
 if(loading&&addresses.length===0)return <Loader/>;
 return <div className="min-h-screen bg-[var(--surface-1)] pt-24 sm:pt-28 pb-20"><SEO title="Saved Addresses | Samridhi Enterprises"/><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
  <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mb-7"><div><p className="text-[10px] uppercase tracking-[.2em] font-extrabold text-blue-600">Delivery preferences</p><h1 className="text-3xl sm:text-4xl font-black tracking-tight">Saved Addresses</h1><p className="text-sm text-[var(--text-muted)] mt-2">Keep your delivery details ready for faster checkout.</p></div><button onClick={openCreate} className="inline-flex items-center justify-center gap-2 h-11 px-5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-sm font-bold"><Plus className="w-4 h-4"/> Add address</button></div>
  {addresses.length===0?<div className="premium-card py-16 text-center"><div className="w-14 h-14 mx-auto rounded-2xl bg-blue-600/10 text-blue-600 grid place-items-center mb-4"><MapPin/></div><h2 className="text-xl font-bold">No saved addresses</h2><p className="text-sm text-[var(--text-muted)] mt-2">Add a delivery address to speed up your next order.</p><button onClick={openCreate} className="mt-5 rounded-xl bg-blue-600 text-white px-5 py-2.5 text-sm font-bold">Add your first address</button></div>:<div className="grid md:grid-cols-2 gap-4">{addresses.map(a=><motion.article key={a._id} layout initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className={`premium-card p-5 ${a.isDefault?"border-blue-500 ring-1 ring-blue-500/20":""}`}><div className="flex justify-between gap-3"><div className="flex items-center gap-3"><span className="w-10 h-10 rounded-xl bg-blue-600/10 text-blue-600 grid place-items-center"><AddressIcon label={a.label}/></span><div><div className="flex items-center gap-2"><span className="text-xs font-extrabold uppercase tracking-wider">{a.label||"Address"}</span>{a.isDefault&&<span className="inline-flex items-center gap-1 text-[9px] font-bold text-blue-600 bg-blue-600/10 rounded-full px-2 py-1"><Star className="w-3 h-3"/>Default</span>}</div><p className="text-sm font-bold mt-1">{a.fullName}</p></div></div><div className="flex gap-1"><button onClick={()=>openEdit(a)} className="w-9 h-9 rounded-lg hover:bg-[var(--surface-2)] text-blue-600 grid place-items-center" aria-label="Edit"><Pencil className="w-4 h-4"/></button><button onClick={()=>setConfirmDelete(a)} className="w-9 h-9 rounded-lg hover:bg-red-500/10 text-red-500 grid place-items-center" aria-label="Delete"><Trash2 className="w-4 h-4"/></button></div></div><div className="mt-4 rounded-xl bg-[var(--surface-2)] p-4 text-sm text-[var(--text-muted)] leading-6"><p>{a.addressLine}</p><p>{a.city}{a.state?`, ${a.state}`:""} — {a.pincode}</p><p>{a.phone}</p></div>{!a.isDefault&&<button onClick={()=>dispatch(setDefaultAddress(a._id))} disabled={actionLoading} className="mt-4 text-xs font-bold text-blue-600 inline-flex items-center gap-1 disabled:opacity-50"><Check className="w-4 h-4"/>Set as default</button>}</motion.article>)}</div>}
 </div>
 {showModal&&<div className="fixed inset-0 z-[100] bg-slate-950/60 backdrop-blur-sm p-4 grid place-items-center"><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="w-full max-w-lg max-h-[90vh] overflow-y-auto rounded-2xl border border-[var(--line)] bg-[var(--surface-0)] shadow-2xl"><div className="p-5 border-b border-[var(--line)] flex justify-between items-center"><div><h2 className="text-lg font-extrabold">{editingId?"Edit address":"Add address"}</h2><p className="text-xs text-[var(--text-muted)] mt-1">Use a complete delivery address.</p></div><button onClick={()=>setShowModal(false)} className="w-9 h-9 rounded-lg hover:bg-[var(--surface-2)] grid place-items-center"><X/></button></div><div className="p-5 space-y-4">{formError&&<div className="rounded-xl bg-red-500/10 border border-red-500/20 text-red-600 px-3 py-2 text-xs font-semibold">{formError}</div>}<div><label className="field-label">Label</label><input name="label" value={form.label} onChange={change} placeholder="Home / Office" className="field-input"/></div><div className="grid sm:grid-cols-2 gap-3"><div><label className="field-label">Full Name *</label><input name="fullName" value={form.fullName} onChange={change} className="field-input"/></div><div><label className="field-label">Phone *</label><input name="phone" value={form.phone} onChange={change} className="field-input"/></div></div><div><label className="field-label">Address *</label><input name="addressLine" value={form.addressLine} onChange={change} className="field-input" placeholder="House no, street, area"/></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div><label className="field-label">City *</label><input name="city" value={form.city} onChange={change} className="field-input"/></div><div><label className="field-label">State</label><input name="state" value={form.state} onChange={change} className="field-input"/></div><div><label className="field-label">Pincode *</label><input name="pincode" value={form.pincode} onChange={change} inputMode="numeric" maxLength={6} className="field-input"/></div></div><label className="flex items-center gap-2 text-sm font-semibold"><input name="isDefault" type="checkbox" checked={form.isDefault} onChange={change} className="accent-blue-600"/>Set as default address</label></div><div className="p-5 border-t border-[var(--line)] flex justify-end gap-2"><button onClick={()=>setShowModal(false)} className="px-4 py-2.5 rounded-xl border border-[var(--line)] text-sm font-semibold">Cancel</button><button onClick={submit} disabled={actionLoading} className="px-5 py-2.5 rounded-xl bg-blue-600 text-white text-sm font-bold disabled:opacity-50">{editingId?"Save changes":"Add address"}</button></div></motion.div></div>}
 {confirmDelete&&<div className="fixed inset-0 z-[100] bg-slate-950/60 backdrop-blur-sm p-4 grid place-items-center"><div className="w-full max-w-sm rounded-2xl bg-[var(--surface-0)] border border-[var(--line)] p-6 shadow-2xl"><h3 className="text-lg font-extrabold">Delete address?</h3><p className="text-sm text-[var(--text-muted)] mt-2">This will permanently remove the saved address for {confirmDelete.fullName}.</p><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setConfirmDelete(null)} className="px-4 py-2.5 rounded-xl border border-[var(--line)] text-sm font-semibold">Cancel</button><button onClick={()=>dispatch(deleteAddress(confirmDelete._id))} className="px-5 py-2.5 rounded-xl bg-red-600 text-white text-sm font-bold">Delete</button></div></div></div>}
 </div>
}
