import { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { toast } from "react-toastify";
import { ClipboardList, Eye, CheckCircle2, XCircle, PackageCheck, Clock3, Truck, CircleDollarSign, Search, MapPin, Phone } from "lucide-react";
import { adminGetAllOrders, adminVerifyPayment, adminUpdateOrderStatus, clearOrderError } from "../../store/order/orderSlice";
import { AdminPageHeader, AdminCard, AdminTable, AdminBadge, AdminSearchInput, AdminModal } from "@/components/admin/AdminUI";
import { Button } from "@/components/ui";

const STATUS_OPTIONS=["","Pending Verification","Confirmed","Processing","Shipped","Delivered","Cancelled"];
const FULFILLMENT=["Confirmed","Processing","Shipped","Delivered","Cancelled"];
const badge=(s)=>["Success","Confirmed","Delivered"].includes(s)?"success":["Pending","Pending Verification","Processing","Shipped"].includes(s)?"warning":["Failed","Cancelled","Rejected"].includes(s)?"danger":"info";
const Stat=({icon:Icon,label,value,tone})=><div className="premium-card p-4"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.15em] font-extrabold text-[var(--text-muted)]">{label}</p><p className="text-xl font-black mt-1">{value}</p></div><span className={`w-9 h-9 rounded-xl grid place-items-center ${tone}`}><Icon className="w-4 h-4"/></span></div></div>;

export default function AdminOrders(){
 const dispatch=useDispatch(); const {adminOrders=[],loading,error}=useSelector(s=>s.order); const [status,setStatus]=useState(""); const [selected,setSelected]=useState(null); const [search,setSearch]=useState(""); const [rejectReason,setRejectReason]=useState(""); const [rejecting,setRejecting]=useState(false);
 useEffect(()=>{dispatch(adminGetAllOrders())},[dispatch]); useEffect(()=>{if(error){toast.error(error);dispatch(clearOrderError())}},[error,dispatch]);
 const filtered=useMemo(()=>adminOrders.filter(o=>{const q=search.toLowerCase().trim();return(!status||o.orderStatus===status)&&(!q||String(o._id).toLowerCase().includes(q)||o.user?.name?.toLowerCase().includes(q)||o.shippingAddress?.fullName?.toLowerCase().includes(q))}),[adminOrders,status,search]);
 const stats=useMemo(()=>({total:adminOrders.length,pending:adminOrders.filter(o=>o.orderStatus==="Pending Verification").length,processing:adminOrders.filter(o=>["Confirmed","Processing"].includes(o.orderStatus)).length,shipped:adminOrders.filter(o=>o.orderStatus==="Shipped").length}),[adminOrders]);
 const verify=(action)=>{if(action==="reject"&&!rejectReason.trim())return toast.error("Enter a rejection reason.");dispatch(adminVerifyPayment({id:selected._id,action,rejectionReason:action==="reject"?rejectReason:undefined})).then(r=>{if(!r.error){toast.success(`Payment ${action}d successfully`);setSelected(null);setRejecting(false);setRejectReason("")}})};
 const updateStatus=(id,newStatus)=>dispatch(adminUpdateOrderStatus({id,status:newStatus})).then(r=>{if(!r.error){toast.success("Order status updated");setSelected(x=>x?{...x,orderStatus:newStatus}:x)}});
 const columns=[{header:"Order"},{header:"Customer"},{header:"Payment"},{header:"Status"},{header:"Total"},{header:"Action",className:"text-right"}];
 return <div className="min-h-screen bg-[var(--surface-1)] p-3 sm:p-5 lg:p-7"><div className="max-w-[1500px] mx-auto space-y-5">
  <AdminPageHeader title="Orders Operations" subtitle="Verify payments and control fulfillment from one workspace." icon={<ClipboardList className="w-6 h-6"/>} badge={`${filtered.length} visible`}/>
  <div className="grid grid-cols-2 xl:grid-cols-4 gap-3"><Stat icon={ClipboardList} label="All orders" value={stats.total} tone="text-blue-600 bg-blue-500/10"/><Stat icon={CircleDollarSign} label="Pending verification" value={stats.pending} tone="text-amber-600 bg-amber-500/10"/><Stat icon={Clock3} label="Processing" value={stats.processing} tone="text-violet-600 bg-violet-500/10"/><Stat icon={Truck} label="Shipped" value={stats.shipped} tone="text-emerald-600 bg-emerald-500/10"/></div>
  <AdminCard className="!p-3"><div className="flex flex-col sm:flex-row gap-2"><AdminSearchInput value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search order ID or customer..." className="w-full sm:flex-1"/><select value={status} onChange={e=>setStatus(e.target.value)} className="h-10 px-3 rounded-xl border border-[var(--line)] bg-[var(--surface-0)] text-sm">{STATUS_OPTIONS.map(x=><option key={x} value={x}>{x||"All statuses"}</option>)}</select></div></AdminCard>
  <AdminCard title="Customer orders" subtitle="Payment, fulfillment and customer details."><AdminTable columns={columns} data={filtered} loading={loading} emptyMessage="No orders match the current filters." renderRow={o=><tr key={o._id} className="hover:bg-[var(--surface-2)] transition"><td className="px-4 py-3 font-mono text-xs font-bold text-blue-600">#{o._id.slice(-8).toUpperCase()}</td><td className="px-4 py-3"><p className="text-sm font-bold">{o.user?.name||o.shippingAddress?.fullName||"Guest"}</p><p className="text-[10px] text-[var(--text-muted)]">{o.shippingAddress?.city||""} {o.shippingAddress?.pincode||""}</p></td><td className="px-4 py-3"><AdminBadge variant={badge(o.paymentStatus)}>{o.paymentStatus}</AdminBadge><p className="text-[10px] text-[var(--text-muted)] mt-1">{o.paymentMethod}</p></td><td className="px-4 py-3"><select value={o.orderStatus} onChange={e=>updateStatus(o._id,e.target.value)} className="px-2 py-1 rounded-lg border border-[var(--line)] bg-[var(--surface-0)] text-xs font-bold">{FULFILLMENT.map(s=><option key={s}>{s}</option>)}</select></td><td className="px-4 py-3 text-sm font-black">₹{o.itemsTotal||o.totalAmount}</td><td className="px-4 py-3 text-right"><Button variant="outline" onClick={()=>{setSelected(o);setRejecting(false);setRejectReason("")}} className="!py-1.5 !px-3 !text-xs !gap-1"><Eye className="w-3.5 h-3.5"/>Details</Button></td></tr>}/></AdminCard>
  <AdminModal isOpen={!!selected} onClose={()=>setSelected(null)} title={`Order #${selected?._id.slice(-8).toUpperCase()}`} maxWidth="max-w-3xl">{selected&&<div className="space-y-5"><div className="grid sm:grid-cols-2 gap-3"><div className="rounded-xl bg-[var(--surface-2)] p-4"><div className="flex gap-2 items-center text-xs font-extrabold mb-2"><MapPin className="w-4 h-4 text-blue-600"/>Shipping</div><p className="text-sm font-bold">{selected.shippingAddress?.fullName}</p><p className="text-xs text-[var(--text-muted)] mt-1">{selected.shippingAddress?.addressLine}</p><p className="text-xs text-[var(--text-muted)]">{selected.shippingAddress?.city}, {selected.shippingAddress?.state} — {selected.shippingAddress?.pincode}</p><p className="text-xs text-[var(--text-muted)] mt-1 flex items-center gap-1"><Phone className="w-3 h-3"/>{selected.shippingAddress?.phone}</p></div><div className="rounded-xl bg-[var(--surface-2)] p-4"><p className="text-xs font-extrabold">Payment</p><p className="text-xs text-[var(--text-muted)] mt-2">Method: <b>{selected.paymentMethod}</b></p><div className="mt-1"><AdminBadge variant={badge(selected.paymentStatus)}>{selected.paymentStatus}</AdminBadge></div>{selected.paymentRejectionReason&&<p className="text-xs text-red-600 mt-2">Reason: {selected.paymentRejectionReason}</p>}</div></div>
   {selected.paymentScreenshot?.url&&<div className="rounded-xl border border-[var(--line)] p-4"><p className="text-xs font-extrabold mb-3">Payment screenshot</p><div className="max-h-64 rounded-xl bg-[var(--surface-2)] flex justify-center overflow-hidden"><img src={selected.paymentScreenshot.url} alt="Payment verification" className="max-h-64 object-contain"/></div>{selected.paymentStatus==="Pending Verification"&&!rejecting&&<div className="flex flex-wrap gap-2 mt-3"><Button variant="primary" onClick={()=>verify("approve")} className="!bg-emerald-600"><CheckCircle2 className="w-4 h-4"/>Approve</Button><Button variant="danger" onClick={()=>setRejecting(true)}><XCircle className="w-4 h-4"/>Reject</Button></div>}{selected.paymentStatus==="Pending Verification"&&rejecting&&<div className="mt-3 flex flex-col sm:flex-row gap-2"><input value={rejectReason} onChange={e=>setRejectReason(e.target.value)} placeholder="Reason for rejection" className="flex-1 h-10 rounded-xl border border-red-300 bg-[var(--surface-0)] px-3 text-sm"/><Button variant="danger" onClick={()=>verify("reject")}>Confirm rejection</Button><Button variant="outline" onClick={()=>setRejecting(false)}>Cancel</Button></div>}</div>}
   <div><div className="flex items-center justify-between mb-2"><h4 className="text-sm font-extrabold">Items ({selected.items?.length||0})</h4><AdminBadge variant={badge(selected.orderStatus)}>{selected.orderStatus}</AdminBadge></div><div className="overflow-x-auto rounded-xl border border-[var(--line)]"><table className="w-full text-xs"><thead className="bg-[var(--surface-2)]"><tr><th className="p-3 text-left">Product</th><th className="p-3">Price</th><th className="p-3">Qty</th><th className="p-3 text-right">Subtotal</th></tr></thead><tbody className="divide-y divide-[var(--line)]">{selected.items?.map((item,i)=><tr key={i}><td className="p-3 font-semibold">{item.name||item.part?.name||"Product"}</td><td className="p-3">₹{item.price}</td><td className="p-3">{item.quantity}</td><td className="p-3 text-right font-bold">₹{item.price*item.quantity}</td></tr>)}</tbody></table></div></div>
  </div>}</AdminModal>
 </div></div>;
}
