import { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Plus, Pencil, Trash2, Tag, Search, TicketPercent, Activity, MousePointerClick } from "lucide-react";
import { toast } from "react-toastify";
import { getAllCoupons, createCoupon, updateCoupon, deleteCoupon, clearCouponError, clearCouponSuccess } from "@/store/order/couponSlice";
import { AdminPageHeader, AdminCard, AdminTable, AdminBadge, AdminModal, AdminSearchInput } from "@/components/admin/AdminUI";
import { Button, Input, Select, Checkbox } from "@/components/ui";

const EMPTY_FORM={code:"",description:"",discountType:"PERCENTAGE",discountValue:"",minOrderAmount:"",maxDiscount:"",expiresAt:"",usageLimit:"",isActive:true};
const statusOf=c=>{if(!c.isActive)return{label:"Inactive",variant:"neutral"};if(c.expiresAt&&new Date(c.expiresAt).getTime()<Date.now())return{label:"Expired",variant:"danger"};if(c.usageLimit>0&&c.usedCount>=c.usageLimit)return{label:"Used up",variant:"warning"};return{label:"Active",variant:"success"}};
const dateLabel=d=>d?new Date(d).toLocaleDateString("en-IN",{year:"numeric",month:"short",day:"numeric"}):"No expiry";
const toFiniteNumber=(v, fallback=0)=>v===""?fallback:Number(v);

export default function AdminCoupons(){
 const dispatch=useDispatch(); const {coupons=[],loading,error,success}=useSelector(s=>s.coupon); const [modal,setModal]=useState(false),[editing,setEditing]=useState(null),[confirmDelete,setConfirmDelete]=useState(null),[form,setForm]=useState(EMPTY_FORM),[errors,setErrors]=useState({}),[search,setSearch]=useState(""),[status,setStatus]=useState("ALL"),[submitting,setSubmitting]=useState(false);
 useEffect(()=>{dispatch(getAllCoupons())},[dispatch]);
 useEffect(()=>{if(success){setModal(false);setEditing(null);setForm(EMPTY_FORM);setErrors({});setSubmitting(false);setConfirmDelete(null);dispatch(clearCouponSuccess())}},[success,dispatch]);
 useEffect(()=>{if(error){toast.error(error);setSubmitting(false);const t=setTimeout(()=>dispatch(clearCouponError()),4000);return()=>clearTimeout(t)}},[error,dispatch]);
 const stats=useMemo(()=>{const active=coupons.filter(c=>statusOf(c).label==="Active").length;const expired=coupons.filter(c=>statusOf(c).label==="Expired").length;return{total:coupons.length,active,expired,redemptions:coupons.reduce((n,c)=>n+Number(c.usedCount||0),0)}},[coupons]);
 const visible=useMemo(()=>coupons.filter(c=>{const q=search.trim().toLowerCase();const st=statusOf(c).label.toUpperCase().replace(" ","_");return(!q||c.code?.toLowerCase().includes(q)||c.description?.toLowerCase().includes(q))&&(status==="ALL"||st===status)}),[coupons,search,status]);
 const openCreate=()=>{setEditing(null);setForm(EMPTY_FORM);setErrors({});setModal(true)};
 const openEdit=c=>{setEditing(c._id);setForm({code:c.code||"",description:c.description||"",discountType:c.discountType||"PERCENTAGE",discountValue:c.discountValue??"",minOrderAmount:c.minOrderAmount??"",maxDiscount:c.maxDiscount??"",expiresAt:c.expiresAt?new Date(c.expiresAt).toISOString().slice(0,10):"",usageLimit:c.usageLimit??"",isActive:c.isActive??true});setErrors({});setModal(true)};
 const change=e=>{const{name,value,type,checked}=e.target;setForm(f=>({...f,[name]:type==="checkbox"?checked:value}));setErrors(e=>({...e,[name]:""}))};
 const submit=async()=>{const e={};const code=form.code.trim().toUpperCase();const discount=toFiniteNumber(form.discountValue);const min=toFiniteNumber(form.minOrderAmount);const cap=toFiniteNumber(form.maxDiscount);const usage=toFiniteNumber(form.usageLimit);if(!/^[A-Z0-9][A-Z0-9_-]{2,30}$/.test(code))e.code="Use 3–31 letters, numbers, hyphens or underscores.";if(!Number.isFinite(discount)||discount<=0)e.discountValue="Discount must be greater than 0.";if(form.discountType==="PERCENTAGE"&&discount>100)e.discountValue="Percentage cannot exceed 100.";if(min<0||!Number.isFinite(min))e.minOrderAmount="Enter a valid minimum order.";if(cap<0||!Number.isFinite(cap))e.maxDiscount="Enter a valid cap.";if(form.discountType==="PERCENTAGE"&&cap>0&&cap<discount&&min>0)e.maxDiscount="Discount cap is unusually low; verify the amount.";if(usage<0||!Number.isInteger(usage))e.usageLimit="Usage limit must be a whole number.";if(form.expiresAt&&new Date(form.expiresAt).getTime()<=Date.now())e.expiresAt="Expiry must be a future date.";if(Object.keys(e).length){setErrors(e);return}const payload={code,description:form.description.trim(),discountType:form.discountType,discountValue:discount,minOrderAmount:min,maxDiscount:cap,expiresAt:form.expiresAt||null,usageLimit:usage,isActive:form.isActive};setSubmitting(true);const action=editing?updateCoupon({id:editing,payload}):createCoupon(payload);const result=await dispatch(action);if(action.type===updateCoupon.typePrefix?updateCoupon.fulfilled.match(result):createCoupon.fulfilled.match(result)){toast.success(editing?"Coupon updated":"Coupon created")}else setSubmitting(false)};
 const remove=async()=>{if(!confirmDelete)return;const result=await dispatch(deleteCoupon(confirmDelete._id));if(deleteCoupon.fulfilled.match(result)){toast.success("Coupon deleted");setConfirmDelete(null)}else toast.error(result.payload?.message||result.payload||"Failed to delete coupon")};
 const cols=[{header:"Code"},{header:"Discount"},{header:"Minimum"},{header:"Expiry"},{header:"Usage"},{header:"Status"},{header:"Actions",className:"text-right"}];
 return <div className="min-h-screen bg-[var(--surface-1)] p-3 sm:p-5 lg:p-7"><div className="max-w-[1500px] mx-auto space-y-5"><AdminPageHeader title="Promotions & Coupons" subtitle="Manage checkout discount codes, campaign validity and redemption limits." icon={<Tag className="w-6 h-6"/>} badge={`${stats.total} coupons`} actions={<Button onClick={openCreate} className="!gap-2"><Plus className="w-4 h-4"/>New Coupon</Button>}/>
 <div className="grid grid-cols-2 xl:grid-cols-4 gap-3 sm:gap-4">{[[TicketPercent,"Total",stats.total,"text-blue-600 bg-blue-500/10"],[Activity,"Active",stats.active,"text-emerald-600 bg-emerald-500/10"],[MousePointerClick,"Redemptions",stats.redemptions,"text-violet-600 bg-violet-500/10"],[Tag,"Expired",stats.expired,"text-rose-600 bg-rose-500/10"]].map(([I,l,v,t])=><div key={l} className="premium-card p-4"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.15em] font-extrabold text-[var(--text-muted)]">{l}</p><p className="text-xl sm:text-2xl font-black mt-2">{v}</p></div><span className={`w-9 h-9 rounded-xl grid place-items-center ${t}`}><I className="w-4 h-4"/></span></div></div>)}</div>
 <AdminCard className="!p-3"><div className="flex flex-col sm:flex-row gap-2"><AdminSearchInput value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search coupon code or description..." className="flex-1"/><select value={status} onChange={e=>setStatus(e.target.value)} className="h-10 rounded-xl border border-[var(--line)] bg-[var(--surface-0)] px-3 text-sm font-semibold"><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="EXPIRED">Expired</option><option value="INACTIVE">Inactive</option><option value="USED_UP">Used up</option></select></div></AdminCard>
 <AdminCard title="All coupons" subtitle="Search, review and manage promotional campaigns."><AdminTable columns={cols} data={visible} loading={loading} emptyMessage="No coupons match your filters." renderRow={c=>{const s=statusOf(c);return <tr key={c._id} className="hover:bg-[var(--surface-2)] transition"><td className="px-4 py-3.5"><p className="font-mono font-black text-blue-600">{c.code}</p>{c.description&&<p className="text-[10px] text-[var(--text-muted)] mt-1 line-clamp-1">{c.description}</p>}</td><td className="px-4 py-3.5 text-sm font-bold">{c.discountType==="PERCENTAGE"?`${c.discountValue}%`:`₹${c.discountValue}`}{c.discountType==="PERCENTAGE"&&c.maxDiscount>0&&<span className="text-[10px] font-normal text-[var(--text-muted)]"> · cap ₹{c.maxDiscount}</span>}</td><td className="px-4 py-3.5 text-sm">{c.minOrderAmount>0?`₹${c.minOrderAmount}`:"—"}</td><td className="px-4 py-3.5 text-xs text-[var(--text-muted)]">{dateLabel(c.expiresAt)}</td><td className="px-4 py-3.5 text-xs font-semibold">{c.usedCount||0}{c.usageLimit>0?` / ${c.usageLimit}`:" / ∞"}</td><td className="px-4 py-3.5"><AdminBadge variant={s.variant}>{s.label}</AdminBadge></td><td className="px-4 py-3.5 text-right"><div className="flex justify-end gap-1"><button onClick={()=>openEdit(c)} aria-label={`Edit ${c.code}`} className="w-8 h-8 rounded-lg text-[var(--text-muted)] hover:text-blue-600 hover:bg-blue-500/10 grid place-items-center"><Pencil className="w-4 h-4"/></button><button onClick={()=>setConfirmDelete(c)} aria-label={`Delete ${c.code}`} className="w-8 h-8 rounded-lg text-[var(--text-muted)] hover:text-rose-600 hover:bg-rose-500/10 grid place-items-center"><Trash2 className="w-4 h-4"/></button></div></td></tr>}}/></AdminCard>
 <AdminModal isOpen={modal} onClose={()=>!submitting&&setModal(false)} title={editing?"Edit Coupon":"Create Coupon"} footer={<><Button variant="outline" onClick={()=>setModal(false)} disabled={submitting}>Cancel</Button><Button onClick={submit} disabled={submitting}>{submitting?(editing?"Saving…":"Creating…"):(editing?"Save Changes":"Create Coupon")}</Button></>}><div className="space-y-4"><Input label="Coupon Code" name="code" value={form.code} onChange={change} placeholder="SAVE20" error={errors.code}/><Input label="Description" name="description" value={form.description} onChange={change} placeholder="Optional campaign description"/><div className="grid grid-cols-2 gap-3"><Select label="Discount Type" name="discountType" value={form.discountType} onChange={change} options={[{value:"PERCENTAGE",label:"Percentage (%)"},{value:"FIXED",label:"Fixed (₹)"}]}/><Input label={form.discountType==="PERCENTAGE"?"Value (%)":"Value (₹)"} name="discountValue" type="number" min="0" value={form.discountValue} onChange={change} error={errors.discountValue}/></div><div className="grid grid-cols-2 gap-3"><Input label="Minimum Order (₹)" name="minOrderAmount" type="number" min="0" value={form.minOrderAmount} onChange={change} error={errors.minOrderAmount}/>{form.discountType==="PERCENTAGE"&&<Input label="Max Discount Cap (₹)" name="maxDiscount" type="number" min="0" value={form.maxDiscount} onChange={change} placeholder="0 = no cap" error={errors.maxDiscount}/>}</div><div className="grid grid-cols-2 gap-3"><Input label="Expiry Date" name="expiresAt" type="date" value={form.expiresAt} onChange={change} error={errors.expiresAt}/><Input label="Usage Limit" name="usageLimit" type="number" min="0" value={form.usageLimit} onChange={change} placeholder="0 = unlimited" error={errors.usageLimit}/></div><Checkbox id="isActive" name="isActive" label="Active (available at checkout)" checked={form.isActive} onChange={change}/></div></AdminModal>
 <AdminModal isOpen={!!confirmDelete} onClose={()=>setConfirmDelete(null)} title="Delete Coupon" footer={<><Button variant="outline" onClick={()=>setConfirmDelete(null)}>Cancel</Button><Button variant="danger" onClick={remove}>Delete</Button></>}><p className="text-sm text-[var(--text-muted)]">Delete <strong className="text-[var(--text-strong)]">{confirmDelete?.code}</strong>? This action cannot be undone.</p></AdminModal>
 </div></div>;
}
