import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Users, UserCheck, UserX, ShieldAlert, ChevronLeft, ChevronRight, Search, ShieldCheck, Clock3 } from "lucide-react";
import { toast } from "react-toastify";
import { getAllUsers, updateUserRole } from "@/store/auth-slice/user";
import { AdminPageHeader, AdminCard, AdminTable, AdminBadge, AdminSearchInput } from "@/components/admin/AdminUI";

const formatDate=(d)=>d?new Date(d).toLocaleDateString("en-IN",{year:"numeric",month:"short",day:"numeric"}):"—";
const roleVariant=(r)=>r==="ADMIN"?"danger":r==="MANAGER"?"info":"neutral";
const statusVariant=(s)=>s==="Active"?"success":s==="Warning"?"warning":s==="Suspended"?"danger":"neutral";
const PAGE_SIZES=[10,25,50];

export default function CustomerPage(){
 const dispatch=useDispatch(); const {users,totalUsers,totalPages,loading,error,user:currentUser}=useSelector(s=>s.auth);
 const [search,setSearch]=useState(""); const [debounced,setDebounced]=useState(""); const [page,setPage]=useState(1); const [limit,setLimit]=useState(10); const [saving,setSaving]=useState(null);
 useEffect(()=>{const t=setTimeout(()=>{setDebounced(search);setPage(1)},350);return()=>clearTimeout(t)},[search]);
 useEffect(()=>{dispatch(getAllUsers({page,limit,search:debounced}))},[dispatch,page,limit,debounced]);
 useEffect(()=>{if(error)toast.error(error)},[error]);
 const list=users||[]; const stats={total:totalUsers||0,active:list.filter(u=>(u.status||"Active")==="Active").length,warning:list.filter(u=>u.status==="Warning").length,suspended:list.filter(u=>u.status==="Suspended").length};
 const changeRole=async(u,role)=>{if(role===u.role)return;if(u._id===currentUser?._id&&role!=="ADMIN")return toast.error("You cannot remove your own admin role.");setSaving(u._id);const r=await dispatch(updateUserRole({email:u.email,role}));setSaving(null);if(updateUserRole.fulfilled.match(r))toast.success(`${u.name}'s role updated to ${role}`);else toast.error(r.payload?.message||r.payload?.error||"Failed to update role")};
 const columns=[{header:"Customer"},{header:"Contact"},{header:"Registered"},{header:"Last Login"},{header:"Role"},{header:"Status"}];
 return <div className="min-h-screen bg-[var(--surface-1)] p-3 sm:p-5 lg:p-7"><div className="max-w-[1500px] mx-auto space-y-5">
  <AdminPageHeader title="Customer Directory" subtitle="Manage customer accounts, roles and access from one workspace." icon={<Users className="w-6 h-6"/>} badge={`${totalUsers||0} Total`}/>
  <div className="grid grid-cols-2 xl:grid-cols-4 gap-3 sm:gap-4">{[[Users,"Registered",stats.total,"text-blue-600 bg-blue-500/10"],[UserCheck,"Active",stats.active,"text-emerald-600 bg-emerald-500/10"],[ShieldAlert,"Warning",stats.warning,"text-amber-600 bg-amber-500/10"],[UserX,"Suspended",stats.suspended,"text-rose-600 bg-rose-500/10"]].map(([Icon,label,value,t],i)=><motion.div key={label} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*.05}} className="premium-card p-4"><div className="flex justify-between items-start"><div><p className="text-[9px] uppercase tracking-[.16em] font-extrabold text-[var(--text-muted)]">{label}</p><p className="text-xl sm:text-2xl font-black mt-2">{loading&&!list.length?"…":value}</p></div><span className={`w-9 h-9 rounded-xl grid place-items-center ${t}`}><Icon className="w-4 h-4"/></span></div></motion.div>)}</div>
  <AdminCard className="!p-3"><div className="flex flex-col lg:flex-row gap-3 lg:items-center"><AdminSearchInput value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name or email..." className="flex-1"/><div className="flex items-center gap-2 text-xs text-[var(--text-muted)]"><span>Rows</span><select value={limit} onChange={e=>{setLimit(Number(e.target.value));setPage(1)}} className="h-10 px-3 rounded-xl border border-[var(--line)] bg-[var(--surface-0)] text-sm font-semibold">{PAGE_SIZES.map(n=><option key={n}>{n}</option>)}</select></div></div></AdminCard>
  <AdminCard title="Registered customers" subtitle="Search, review and manage account access."><AdminTable columns={columns} data={list} loading={loading} emptyMessage="No customer accounts match your search." renderRow={u=><tr key={u._id} className="hover:bg-[var(--surface-2)] transition-colors"><td className="px-4 py-3.5"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-xl overflow-hidden bg-blue-600/10 text-blue-600 grid place-items-center font-black text-xs shrink-0">{u.avatar?<img src={u.avatar} alt={u.name||"Customer"} className="w-full h-full object-cover"/>:(u.name||"?")[0].toUpperCase()}</div><div><p className="text-sm font-bold">{u.name||"Unnamed customer"}</p><p className="text-[10px] text-[var(--text-muted)] flex items-center gap-1"><Clock3 className="w-3 h-3"/>{u.lastLogin?`Last active ${formatDate(u.lastLogin)}`:"No login recorded"}</p></div></div></td><td className="px-4 py-3.5 text-sm text-[var(--text-muted)] break-all">{u.email||"—"}</td><td className="px-4 py-3.5 text-xs text-[var(--text-muted)]">{formatDate(u.createdAt)}</td><td className="px-4 py-3.5 text-xs text-[var(--text-muted)]">{formatDate(u.lastLogin)}</td><td className="px-4 py-3.5">{currentUser?.role==="ADMIN"?<select value={u.role} disabled={saving===u._id} onChange={e=>changeRole(u,e.target.value)} className="h-8 px-2 rounded-lg border border-[var(--line)] bg-[var(--surface-0)] text-xs font-bold">{["USER","MANAGER","ADMIN"].map(r=><option key={r}>{r}</option>)}</select>:<AdminBadge variant={roleVariant(u.role)}>{u.role}</AdminBadge>}</td><td className="px-4 py-3.5"><AdminBadge variant={statusVariant(u.status)}>{u.status||"Active"}</AdminBadge></td></tr>}/></AdminCard>
  {totalPages>1&&<div className="flex items-center justify-center gap-3"><button disabled={page===1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="w-9 h-9 rounded-lg border border-[var(--line)] grid place-items-center disabled:opacity-40"><ChevronLeft className="w-4 h-4"/></button><span className="text-xs font-bold text-[var(--text-muted)]">Page {page} of {totalPages}</span><button disabled={page===totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))} className="w-9 h-9 rounded-lg border border-[var(--line)] grid place-items-center disabled:opacity-40"><ChevronRight className="w-4 h-4"/></button></div>}
 </div></div>;
}
