import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { useDispatch, useSelector } from "react-redux";
import { Link } from "react-router-dom";
import { AlertTriangle, ArrowUpRight, Boxes, Package, PackageCheck, PackageX, Search, Warehouse } from "lucide-react";
import { toast } from "react-toastify";
import { adminGetInventory, clearOrderError } from "@/store/order/orderSlice";
import { AdminCard, AdminPageHeader, AdminBadge } from "@/components/admin/AdminUI";

const money=(n)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n)||0);
const badge=(s)=>s==="Out of Stock"?"danger":s==="Low Stock"?"warning":"success";
const filters=["All","In Stock","Low Stock","Out of Stock"];

export default function PremiumInventoryPage(){
 const dispatch=useDispatch(); const {inventory=[],loading,error}=useSelector(s=>s.order); const [filter,setFilter]=useState("All"); const [query,setQuery]=useState("");
 useEffect(()=>{dispatch(adminGetInventory())},[dispatch]);
 useEffect(()=>{if(error){toast.error(error);dispatch(clearOrderError())}},[error,dispatch]);
 const stats=useMemo(()=>{const total=inventory.length;const inStock=inventory.filter(p=>p.status==="In Stock").length;const low=inventory.filter(p=>p.status==="Low Stock").length;const out=inventory.filter(p=>p.status==="Out of Stock").length;const units=inventory.reduce((n,p)=>n+Number(p.stock||0),0);const value=inventory.reduce((n,p)=>n+Number(p.price||0)*Number(p.stock||0),0);return{total,inStock,low,out,units,value}},[inventory]);
 const rows=useMemo(()=>{const q=query.trim().toLowerCase();return inventory.filter(p=>(filter==="All"||p.status===filter)&&(!q||[p.name,p.category,p.product_id].some(v=>String(v||"").toLowerCase().includes(q))))},[inventory,filter,query]);
 const cards=[["Products",stats.total,Boxes,"text-blue-600 bg-blue-500/10"],["Units on hand",stats.units,Package,"text-violet-600 bg-violet-500/10"],["Low stock",stats.low,AlertTriangle,"text-amber-600 bg-amber-500/10"],["Out of stock",stats.out,PackageX,"text-red-600 bg-red-500/10"]];
 return <div className="min-h-screen bg-[var(--surface-1)] p-3 sm:p-5 lg:p-7"><div className="max-w-[1500px] mx-auto space-y-5">
  <AdminPageHeader title="Inventory Control" subtitle="Monitor stock health and identify products that need attention." icon={<Warehouse className="w-6 h-6"/>} badge={loading?"Updating…":`${rows.length} visible`}/>
  <div className="grid grid-cols-2 xl:grid-cols-4 gap-3">{cards.map(([label,value,Icon,t],i)=><motion.div key={label} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*.05}} className="premium-card p-4 sm:p-5"><div className="flex items-start justify-between"><div><p className="text-[9px] uppercase tracking-[.15em] font-extrabold text-[var(--text-muted)]">{label}</p><p className="text-xl sm:text-2xl font-black mt-2">{loading&&!inventory.length?"…":value}</p></div><span className={`w-9 h-9 rounded-xl grid place-items-center ${t}`}><Icon className="w-4 h-4"/></span></div></motion.div>)}</div>
  <div className="grid lg:grid-cols-[1.3fr_.7fr] gap-5"><AdminCard title="Inventory value" subtitle="Current catalogue price multiplied by quantity on hand."><div className="flex items-center justify-between gap-4"><div><p className="text-3xl font-black">{money(stats.value)}</p><p className="text-xs text-[var(--text-muted)] mt-1">Across {stats.total} catalogue products</p></div><span className="w-12 h-12 rounded-2xl bg-emerald-500/10 text-emerald-600 grid place-items-center"><PackageCheck/></span></div></AdminCard><AdminCard title="Restock signals" subtitle="Prioritize these products first."><div className="space-y-2"><div className="rounded-xl bg-amber-500/10 p-3 flex justify-between"><span className="text-xs font-semibold">Low stock</span><b className="text-amber-600">{stats.low}</b></div><div className="rounded-xl bg-red-500/10 p-3 flex justify-between"><span className="text-xs font-semibold">Out of stock</span><b className="text-red-600">{stats.out}</b></div><Link to="/admin/parts" className="text-xs font-bold text-blue-600 inline-flex items-center gap-1 mt-1">Manage parts <ArrowUpRight className="w-3.5 h-3.5"/></Link></div></AdminCard></div>
  <AdminCard title="Stock monitoring" subtitle="Search and filter the live inventory feed."><div className="flex flex-col lg:flex-row gap-3 mb-4"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[var(--text-muted)]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product, category or ID…" className="w-full h-10 pl-10 pr-3 rounded-xl border border-[var(--line)] bg-[var(--surface-0)] text-sm outline-none focus:ring-2 focus:ring-blue-500"/></div><div className="flex flex-wrap gap-2">{filters.map(f=><button key={f} onClick={()=>setFilter(f)} className={`h-10 px-3 rounded-xl border text-xs font-bold ${filter===f?"bg-blue-600 text-white border-blue-600":"border-[var(--line)] bg-[var(--surface-0)] text-[var(--text-muted)]"}`}>{f}</button>)}</div></div><div className="overflow-x-auto rounded-xl border border-[var(--line)]"><table className="w-full text-sm"><thead className="bg-[var(--surface-2)]"><tr><th className="p-3 text-left text-[10px] uppercase tracking-wider">Product</th><th className="p-3 text-left text-[10px] uppercase tracking-wider">Category</th><th className="p-3 text-right text-[10px] uppercase tracking-wider">Price</th><th className="p-3 text-right text-[10px] uppercase tracking-wider">Stock</th><th className="p-3 text-center text-[10px] uppercase tracking-wider">Status</th></tr></thead><tbody className="divide-y divide-[var(--line)]">{rows.map(p=><tr key={p._id} className="hover:bg-[var(--surface-2)]"><td className="p-3"><Link to={`/products/${p._id}`} className="font-bold hover:text-blue-600">{p.name}</Link><p className="text-[9px] text-[var(--text-muted)]">{p.product_id||p._id}</p></td><td className="p-3 text-xs text-[var(--text-muted)]">{p.category||"—"}</td><td className="p-3 text-right font-semibold">{money(p.price)}</td><td className="p-3 text-right font-black">{p.stock}</td><td className="p-3 text-center"><AdminBadge variant={badge(p.status)}>{p.status}</AdminBadge></td></tr>)}</tbody></table>{!rows.length&&!loading&&<div className="py-12 text-center text-sm text-[var(--text-muted)]">No products match the current filters.</div>}</div></AdminCard>
  </div></div>;
}
