name: Pull Request Verification

on:
  pull_request:
    branches:
      - main

jobs:
  verify-client:
    name: Verify Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 20
          package-manager-cache: false

      - name: Install Client Dependencies
        run: npm install
        working-directory: client

      - name: Run Lint
        run: npm run lint
        working-directory: client

      - name: Build Client
        run: npm run build
        working-directory: client

  verify-server:
    name: Verify Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 20
          package-manager-cache: false

      - name: Install Server Dependencies
        run: npm install
        working-directory: server
